#!/usr/bin/env zsh
 
# Complétion
autoload -U compinit
compinit
 
#Insensible à la casse
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}'
 
#compinstall
zstyle ':completion:*:descriptions' format '%U%B%d%b%u'
zstyle ':completion:*:warnings' format '%BSorry, no matches for: %d%b'
zstyle ':completion:*:sudo:*' command-path /usr/local/sbin /usr/local/bin \
                             /usr/sbin /usr/bin /sbin /bin /usr/X11R6/bin
# Crée un cache des complétion possibles
# très utile pour les complétion qui demandent beaucoup de temps
# comme la recherche d'un paquet aptitude install moz<tab>
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh_cache
# des couleurs pour la complétion
# faites un kill -9 <tab><tab> pour voir :)
zmodload zsh/complist
setopt extendedglob
zstyle ':completion:*:*:kill:*:processes' list-colors "=(#b) #([0-9]#)*=36=31"
 
# Correction des commandes
setopt correctall
 
autoload colors; colors
#export PS1="%B[%{$fg[red]%}%n%{$reset_color%}%b@%B%{$fg[cyan]%}%m%b%{$reset_color%}:%~%B]%b "
 
# Les alias marchent comme sous bash
alias ls='ls --color=auto'
alias ll='ls --color=auto -lh'
alias lll='ls --color=exitauto -lh | less'
# marre de se faire corriger par zsh ;)
alias xs='cd'
alias sl='ls'
# Alias df -h
alias df='df -h'
# Un grep avec des couleurs :
export GREP_COLOR=31
alias grep='grep --color=auto'
 
# un VRAI éditeur de texte ;)
export EDITOR=/usr/bin/vim
 
#Activer l'historique des commandes:
HISTFILE=~/.zsh_history
HISTSIZE=1000
SAVEHIST=1000
export HISTFILE SAVEHIST

#---------- DEFINITION DES FONCTIONS ----------

# Récupérer la branche git si c'est un dépôt :
function info_git () {
    if [[ -d .git ]] ; then
        gitb="%F{yellow}($(git rev-parse --abbrev-ref HEAD))%f"
        if [[ $?  -ne 0 ]] || [[ -z "$gitb" ]] ; then
            return
        fi
    else
        gitb=""
    fi
    print $gitb
}

#---------- CONSTRUCTION DU PROMPT ----------

if [[ $UID -eq 0 ]]; then
    local user_host='%F{red}%n%f (%m):'
    local user_symbol='%F{red}#%f'
else
    local user_host='%F{green}%n%f (%m):'
    local user_symbol='%F{green}$%f'
fi


# prompt gauche
PROMPT="╭─%f[${user_host} %F{yellow}%~%f]
╰─%f ${user_symbol} "
# prompt droit
RPROMPT='%(?..%F{red}(%?%)%f)$(info_git)[%B%F{cyan}%*%f]'

# Indispensable pour assurer l'extension des résultats des commandes
setopt prompt_subst
autoload -U promptinit
